### ISSUE TITLE
TimeoutError at Object.fetchUntilMergeBase

### ISSUE THREAD

**Issue by dvyukov** [pascalgn/automerge-action#115]
Hello,

I've tried to use this action and it fails for me. Not sure if I am doing something wrong, or there is an issue with the action. Will appreciate any help.

PR that adds the action is:
https://github.com/google/syzkaller/pull/2169

I always fails with (tried to re-run several times):
```
INFO  Updating PR #2169 .github/workflows: add auto-merge action
ERROR TimeoutError
    at Object.fetchUntilMergeBase (/usr/local/share/.config/yarn/global/node_modules/automerge-action/lib/git.js:116:9)
    at processTicksAndRejections (internal/process/task_queues.js:86:5)
```

Current version of the config is:
```
name: automerge
on:
  pull_request:
    types:
      - labeled
      - unlabeled
      - synchronize
      - opened
      - edited
      - ready_for_review
      - reopened
      - unlocked
  pull_request_review:
    types:
      - submitted
  check_suite:
    types:
      - completed
  status: {}
jobs:
  automerge:
    runs-on: ubuntu-latest
    steps:
      - name: automerge
        uses: "pascalgn/automerge-action@v0.11.0"
        env:
          GITHUB_TOKEN: "${{ secrets.GITHUB_TOKEN }}"
          MERGE_METHOD_LABELS: "autocommit=rebase,autosquash=squash"
          MERGE_METHOD_LABEL_REQUIRED: true
          UPDATE_METHOD: "rebase"
          UPDATE_LABELS: ""
```
