### ISSUE TITLE
Allow to ignore Draft PRs

### ISSUE THREAD

**Issue by vladimirf7** [pascalgn/automerge-action#123]
Would be nice to have an option to ignore [draft PRs](https://github.blog/2019-02-14-introducing-draft-pull-requests/)

**Comment by kymikoloco** [comment]
You can edit your workflow `yaml` file to [add an if check](https://docs.github.com/en/free-pro-team@latest/actions/reference/context-and-expression-syntax-for-github-actions#operators) not even run the check when a PR is in draft, and also only run when the label is on the PR, instead of running constantly only to do no work.
```yaml
name: automerge
on:
  pull_request:
    <...>
jobs:
  automerge:
    runs-on: ubuntu-latest
    if: contains(github.event.pull_request.labels.*.name, 'automerge') && github.event.pull_request.draft == false
    steps:
      - name: automerge
        uses: "pascalgn/automerge-action@v0.12.0"
        <...>
```
