### ISSUE TITLE
Check PR on another branch?

### ISSUE THREAD

**Issue by ericknyoto** [pascalgn/automerge-action#126]
Hi there,
Can this action check if PR are exist on another branch instead of the current branch and merge it?
Because I added action pull request targeting branch 'staging' and, when I ran this actions, it said no PR from current branch.
I can also confirm that the PR were created on branch staging.

**Comment by pascalgn** [comment]
We will need more details here. I'm not sure if I understood you correctly, but in general, if your default branch is e.g. `main` and you have a PR merging from "some-br-branch" into "develop" (not main) then the automerge-action will still merge it

**Comment by ericknyoto** [comment]
Sorry, Here is my workflow file. To get you better understand what I mean.
I pushed commit to branch called "feature" and I want to create a pull request to branch "development" and automatically merge the pull request.

But the auto-merge action give information that:
"2020-11-25T10:44:46.674Z INFO  No open PRs for feature"
```
name: automerge
on: [push]
jobs:
  run-test:
    steps:
      - name: Checkout current branch
        uses: actions/checkout@v2
  pullrequest:
    needs: [run-test]
    runs-on: self-hosted
    steps:
      - name: Checkout current branch
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Get current branch name
        shell: bash
        run: echo "::set-output name=branch::${GITHUB_REF#refs/heads/}"
        id: branch_name
      - name: Create Pull Request to staging
        uses: repo-sync/pull-request@v2
        with:
          destination_branch: "development"
          source_branch: ${{ steps.branch_name.outputs.branch }}
          pr_label: "automerge"
```
