### ISSUE TITLE
Running on branches not involved in any PR repeatedly

### ISSUE THREAD

**Issue by mtfurlan** [pascalgn/automerge-action#127]
I'm having an issue where the automerge action is running a lot on my develop branch *and* a PR when a PR is updated.
Removing 
```
on:
...
  status: {}
```
seems to make it not do that.

It's in the example action yaml in the README, but it seems like it isn't needed and does extra stuff that isn't wanted?
Am I missing something or is it safe to remove that trigger?

**Comment by raphodn** [comment]
I was having similar issues, where `automerge` action would run on pushes to `master`, as well as spawning multiple workflows at the same time. I don't know if this has been happening recently or not though..

I upgraded to v0.12.0, and removed the `status: {}` line, and it seems to have fixed it 🙏

**Comment by pascalgn** [comment]
The `status: {}` line is needed for workflows where you have an external build tool configured, for example Jenkins, CircleCI or Travis CI: when that external build is finished, it will report to GitHub, which will trigger the `status` event and the automerge-action is triggered and (depending on the configuration) will merge the branch.

If you don't have this workflow, you can remove it of course :)

**Comment by mtfurlan** [comment]
Ah, I see.

Looking at [the docs](https://docs.github.com/en/free-pro-team@latest/rest/reference/repos#statuses) the possible statuses are `error`, `failure`, `pending`, or `success`.
Could we filter on only `success`, because if it's any of the other statuses automerge shouldn't run?

**Comment by mtfurlan** [comment]
I finally found the right docs for [the status trigger](https://docs.github.com/en/free-pro-team@latest/actions/reference/events-that-trigger-workflows#status) and it suggests that filtering isn't possible.
I guess we just have to live with the action getting run repeatedly.

**Comment by mtfurlan** [comment]
The solution I ended up with is a running some checks in the workflow syntax, running some checks with api calls, all in a seperate job before the automerge job runs so it never builds the image if it doesn't have to, as building the image takes a fair chunk of time.
```yaml
# Things I want to trigger on:
# * PR approval
# * PR label added
# * status checks passing
#
# Things I do not want to run on
# * commits not from a PR
# * status check changes other than success
#
# doc: https://docs.github.com/en/actions/reference/workflow-syntax-for-github-actions
name: automerge
# code later on assumes we are either triggered via status or
# an event that has pull_request.head.sha (pull_request or pull_request_review)
on:
  pull_request:
    types:
      - labeled
  pull_request_review:
    types:
      - submitted
  status: {}
jobs:
  #this job prints out all the context that could possibly be useful
  #debug:
  #  runs-on: ubuntu-latest
  #  if: ${{ (github.event_name != 'status' || github.event.state == 'success') }}
  #  steps:
  #    - name: info
  #      run: |
  #        echo "EVENT_NAME: $EVENT_NAME"
  #        echo "STATUS_STATE: $STATUS_STATE"
  #        echo "REPO: $REPO"
  #        echo "PR_SHA: $PR_SHA"
  #        echo "STATUS_SHA: $STATUS_SHA"
  #        echo "REF: $REF"
  #        echo "GITHUB_CONTEXT: $GITHUB_CONTEXT"
  #        echo "JOB_CONTEXT: $JOB_CONTEXT"
  #        echo "STEPS_CONTEXT: $STEPS_CONTEXT"
  #        echo "RUNNER_CONTEXT: $RUNNER_CONTEXT"
  #        echo "STRATEGY_CONTEXT: $STRATEGY_CONTEXT"
  #        echo "MATRIX_CONTEXT: $MATRIX_CONTEXT"
  #        echo "contents of GITHUB_EVENT_PATH file:"
  #        cat $GITHUB_EVENT_PATH
  #      env:
  #        EVENT_NAME: "${{ github.event_name }}"
  #        STATUS_STATE: "${{ github.event.state }}"
  #        REPO: "${{ github.repository }}"
  #        PR_SHA: "${{ github.event.pull_request.head.sha }}"
  #        STATUS_SHA: "${{ github.event.sha }}"
  #        REF: "${{ github.ref }}"
  #        GITHUB_CONTEXT: ${{ toJson(github) }}
  #        JOB_CONTEXT: ${{ toJson(job) }}
  #        STEPS_CONTEXT: ${{ toJson(steps) }}
  #        RUNNER_CONTEXT: ${{ toJson(runner) }}
  #        STRATEGY_CONTEXT: ${{ toJson(strategy) }}
  #        MATRIX_CONTEXT: ${{ toJson(matrix) }}

  decideIfGoodPR:
    # github.sha is the last commit on the default branch, so if the github.event.sha
    # matches github.sha, we are on the default branch and don't want to run
    # Also if the status wasn't successful we don't want to run
    if: ${{ (github.event_name != 'status' || (github.event.state == 'success' && github.sha != github.event.sha)) }}
    runs-on: ubuntu-latest
    outputs:
      good: ${{ steps.saveResult.outputs.good }}
    steps:
      - name: getSHA
        env:
          EVENT_NAME: "${{ github.event_name }}"
          PR_SHA: "${{ github.event.pull_request.head.sha }}"
          STATUS_SHA: "${{ github.event.sha }}"
        run: |
          [[ "$EVENT_NAME" = "status" ]] && sha="$STATUS_SHA" || sha="$PR_SHA"
          echo "SHA=$sha" >> $GITHUB_ENV

      - name: decideIfPR
        env:
          SHA: "${{ env.SHA }}"
          REPO: "${{ github.repository }}"
        run: |
          json=$(curl --silent -G \
          --header 'authorization: Bearer ${{ secrets.GITHUB_TOKEN }}' \
          --header "Accept: application/vnd.github.v3+json" \
          "https://api.github.com/search/issues?q=repo:$REPO+is:open+is:pr+sha:$SHA")
          result=$(echo "$json" | jq -r '.total_count != 0')
          echo "IS_PR=$result" >> $GITHUB_ENV

      - name: decideIfCommitPassing
        env:
          SHA: "${{ env.SHA }}"
          REPO: "${{ github.repository }}"
        run: |
          json=$(curl --silent -G \
          --header 'authorization: Bearer ${{ secrets.GITHUB_TOKEN }}' \
          --header "Accept: application/vnd.github.v3+json" \
          "https://api.github.com/repos/$REPO/commits/$SHA/status")
          echo "reponse: '$json'"
          result=$(echo "$json" | jq -r '.state == "success"')
          echo "COMMIT_PASSING=$result" >> $GITHUB_ENV

      - name: combineResults
        run: |
          if [[ "${{ env.IS_PR }}" = "true" && "${{ env.COMMIT_PASSING }}" = "true" ]]; then
            echo "GOOD=true" >> $GITHUB_ENV
          else
            echo "GOOD=false" >> $GITHUB_ENV
          fi

      - id: saveResult # need to set step outputs on their own for some reason?
        run: echo "::set-output name=good::${{ env.GOOD }}"

      #- name: debug
      #  run: |
      #    echo "STEPS: $STEPS"
      #    echo "is pr: ${{ env.IS_PR }}"
      #    echo "passing: ${{ env.COMMIT_PASSING }}"
      #  env:
      #    STEPS: ${{ toJson(steps) }}

  automerge:
    needs: decideIfGoodPR
    if: ${{ needs.decideIfGoodPR.outputs.good == 'true' }}
    runs-on: ubuntu-latest
    steps:
      - name: automerge
        uses: "pascalgn/automerge-action@v0.12.0"
        env:
          GITHUB_TOKEN: "${{ secrets.GITHUB_TOKEN }}"
          MERGE_LABELS: "automerge"
          MERGE_REMOVE_LABELS: "automerge"
          MERGE_METHOD: "squash"
          UPDATE_METHOD: "merge"
          MERGE_COMMIT_MESSAGE: "pull-request-title-and-description"
          MERGE_COMMIT_MESSAGE_REGEX: "(.*)\n^\\*\\*\\*\\*"
```
