### ISSUE TITLE
Does not merge if bot creates the label

### ISSUE THREAD

**Issue by YonatanKra** [pascalgn/automerge-action#131]
Hi,
I've created a simple flow that adds a label to the PR and then tries to merge it.
It doesn't work.
If I run the same flow but set the merge on my own, it works.
Here's my flow:
```
name: Test and Build

on:
  pull_request:
    branches:
      - main

jobs:
  cache-yarn:
    runs-on: ubuntu-20.04

    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          token: ${{ secrets.PAT }}

      - name: Setup NodeJS 12
        uses: actions/setup-node@v1
        with:
          node-version: 12

      - name: Install yarn
        run: npm install -g yarn

      - name: Cache yarn dependencies
        uses: actions/cache@v2
        id: yarn-cache
        with:
          path: |
            ${{ steps.yarn-cache-dir-path.outputs.dir }}
            **\node_modules
          key: vivid-cache-yarn-${{ hashFiles('**/yarn.lock') }}
          restore-keys: |
            vivid-cache-yarn-

      - name: Install packages
        if: steps.yarn-cache.outputs.cache-hit != 'true'
        run: yarn install

  build-test:
    needs: cache-yarn
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Setup NodeJS 14
        uses: actions/setup-node@v1
        with:
          node-version: 14

      - name: Install yarn
        run: npm install -g yarn

      - name: Install packages
        if: steps.yarn-cache.outputs.cache-hit != 'true'
        run: yarn install

      - name: Test
        run: yarn test:ci

      - name: Add automerge label
        if: ${{ !contains(github.event.comment.body, '/automerge') }}
        uses: actions-ecosystem/action-add-labels@v1
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          labels: automerge

  auto-merge:
    needs: build-test
    runs-on: ubuntu-latest
    steps:
      - name: automerge
        uses: "pascalgn/automerge-action@v0.12.0"
        env:
          GITHUB_TOKEN: "${{ secrets.GITHUB_TOKEN }}"
          MERGE_LABELS: "automerge"
          MERGE_REMOVE_LABELS: "automerge"
          MERGE_METHOD: "squash"
          MERGE_COMMIT_MESSAGE: "pull-request-title"

```
The last step of the test and build is to add the label. It does add the label - but then when it gets to the auto-merge job it doesn't work.
Is there a way to make it work this way?

**Comment by pascalgn** [comment]
>but then when it gets to the auto-merge job it doesn't work

Could you give us more details what exactly it is that doesn't work?

**Comment by ayumitamai97** [comment]
I'm having the same issue.

I use [`peter-evans/create-pull-request@v3`](https://github.com/peter-evans/create-pull-request) to create Pull Request and add a label to it. This means github-actions bot creates the label.

When github-actions bot creates PR and adds `automerge` label to it, automerge workflow is not triggered. 
But when I add `automerge` label to the same PR, automerge workflow is triggered.

---

Here is my GitHub Action which uses `peter-evans/create-pull-request@v3`:
```yaml
name: Update GraphQL Schema

on:
  repository_dispatch:
    types: [update-graphql-schema]

jobs:
  update-graphql-schema:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v2

      # Some jobs

      - name: Create Pull Request
        id: cpr
        uses: peter-evans/create-pull-request@v3
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          commit-message: '[GitHub Actions] Update GraphQL Schema'
          committer: GitHub <noreply@github.com>
          author: ${{ github.actor }} <${{ github.actor }}@users.noreply.github.com>
          signoff: false
          branch: feature/update-graphql-schema
          branch-suffix: timestamp
          delete-branch: true
          title: 'Update GraphQL Schema'
          body: GraphQL schema has been updated
          labels: automerge # Bot adds label to the Pull Request
``` 

And this is config for automerge (exactly same as [this example in the README](https://github.com/pascalgn/automerge-action#usage)):
```yaml
name: automerge
on:
  pull_request:
    types:
      - labeled
      - unlabeled
      - synchronize
      - opened
      - edited
      - ready_for_review
      - reopened
      - unlocked
  pull_request_review:
    types:
      - submitted
  check_suite:
    types:
      - completed
  status: {}
jobs:
  automerge:
    runs-on: ubuntu-latest
    steps:
      - name: automerge
        uses: "pascalgn/automerge-action@v0.13.0"
        env:
          GITHUB_TOKEN: "${{ secrets.GITHUB_TOKEN }}"
```

Given the configuration above, github-actions bot creates a new PR and adds `automerge` label to it. But as you see automerge workflow does not run.

<img width="1792" alt="スクリーンショット 2021-01-28 20 48 55" src="https://user-images.githubusercontent.com/29456740/106135053-bc837b00-61aa-11eb-84a0-982f5b612064.png">

As I remove/add `automerge` to the PR myself, automerge workflow starts to run and merges the PR.
<img width="1792" alt="スクリーンショット 2021-01-28 20 53 12" src="https://user-images.githubusercontent.com/29456740/106135229-f8b6db80-61aa-11eb-80c4-a59a1a5cfc98.png">


https://github.com/ayumitamai97/cont-codegen-sandbox-client/pull/9

**Comment by ayumitamai97** [comment]
Maybe this is not the bug of automerge-action.

The reason why automerge is not triggered is that github-actions bot labeling does not trigger `labeled` event, which is expected behavior of github-actions.

https://github.community/t/github-actions-bot-labeling-triggers-not-the-issue-labeled-event/16995

**Comment by zeshuaro** [comment]
I had the same issue and was able to get it working with using a personal access token (PAT), similar to @ayumitamai97 approach. All you have to do is to to use PAT in the workflow that creates the PR, something like this should be sufficient:

```yml
- uses: actions/checkout@v2
  with:
    token: ${{ secrets.PAT }}
```

And I didn't have to do anything special with my automerge workflow config.

**Comment by pmkuny** [comment]
Encountering the same problem, unfortunately @zeshuaro 's solution didn't work for me. I've successfully confirmed the PRs are created (as myself, using my personal token), but automerge is still reporting "No PRs have been merged/updated"

```
# Create Pull Request after formatting

      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v2
        with:
          token: ${{ secrets.PAT }}
          commit-message: terraform fmt
          title: Reformat terraform files
          body: Update terraform files to canonical format using `terraform fmt`
          labels: "automerge"
```
```
# Automerge labeled pull requests:
name: Automerge Terraform Format PRs
on:
  workflow_run:
    workflows: ["Terraform Format"]
    branches: [ "main" ]
    types:
      - completed
jobs:
  automerge:
    runs-on: ubuntu-latest
    steps:
      - name: automerge
        uses: "pascalgn/automerge-action@v0.14.2"
        env:
          GITHUB_TOKEN: "${{ secrets.GITHUB_TOKEN }}"
```

**Comment by zeshuaro** [comment]
@pmkuny You should use the token in the workflow that creates the PR, instead of the automerge workflow.

**Comment by zeshuaro** [comment]
@pmkuny Can you try using the PAT token in the checkout action instead of the create PR action?

**Comment by pmkuny** [comment]
@zeshuaro Apologies, I am. I should have included that. Here's my whole file:

```
jobs:
  tffmt:
    name: Execute Terraform Format
    env:
      ACTIONS_ALLOW_UNSECURE_COMMANDS: true
    runs-on: ubuntu-latest
    steps:
      - name: Code Checkout
        uses: actions/checkout@v2
        with:
          token: ${{ secrets.PAT  }}
      - name: Install Terraform
        run: wget https://releases.hashicorp.com/terraform/0.15.5/terraform_0.15.5_linux_amd64.zip
      - name: Install Terraform (unzip)
        run: unzip terraform*.zip
      - name: chmod TF
        run: chmod +x ./terraform
      - name: Terraform Format
        run: ./terraform fmt -recursive
      - name: Remove Binaries
        run: rm ./terraform && rm terraform*.zip
      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v2
        with:
          token: ${{ secrets.PAT }}
          commit-message: terraform fmt
          title: Reformat terraform files
          body: Update terraform files to canonical format using `terraform fmt`
          labels: "automerge"
```
