### ISSUE TITLE
ERROR Bad credentials

### ISSUE THREAD

**Issue by iamroddo** [pascalgn/automerge-action#138]
I have created a personal token and stored it in secrets of the repo which hosts this workflow, with the name ACTIONS_TEST_GITHUB_TOKEN. I use this secret in another workflow successfully (to add a tag). The token bearer has access to "repo". The repo is in GHE and I have cloned the GH action repo into a GHE org.

When I execute the workflow, it produces the error "ERROR Bad credentials".

The workflow is as below.
```
name: automerge
on:
  pull_request:
    types:
      - labeled
      - unlabeled
      - synchronize
      - opened
      - edited
      - ready_for_review
      - reopened
      - unlocked
  pull_request_review:
    types:
      - submitted
  check_suite:
    types:
      - completed
  status: {}
jobs:
  automerge:
    runs-on:
      - self-hosted
    steps:
      - name: automerge
        uses: "netinfra/automerge-action@v0.13.0"
        env:
          GITHUB_TOKEN: ${{ secrets.ACTIONS_TEST_GITHUB_TOKEN }}
          MERGE_METHOD: squash
```
