### ISSUE TITLE
Status check not triggering

### ISSUE THREAD

**Issue by mustafashabib** [pascalgn/automerge-action#153]
Hey all - I'm sure this is documented somewhere but having trouble figuring something out and thought to ask.

Our config looks like this: 
```
name: automerge
on:
  pull_request:
    types:
      - labeled
      - unlabeled
      - synchronize
      - opened
      - edited
      - ready_for_review
      - reopened
      - unlocked
  pull_request_review:
    types:
      - submitted
  check_suite:
    types:
      - completed
  status: {}
jobs:
  automerge:
    runs-on: ubuntu-latest
    steps:
      - name: automerge
        uses: "pascalgn/automerge-action@v0.14.1"
        env:
          GITHUB_TOKEN: "${{ secrets.AUTOMERGE_ACCESS_TOKEN }}"
          MERGE_LABELS: "automerge,!work in progress,!wip"
          MERGE_REMOVE_LABELS: "automerge"
          MERGE_METHOD: "squash"
          MERGE_FORKS: "false"
          UPDATE_LABELS: "automerge"

```

And I'm noticing that automerge is not triggering when all status checks have completed. This means that if you give a review to a PR and "approve" it but one of our status checks is still running (unit tests or something) then it doesn't actually automerge it when that check completes. Is that something due to how my status check is triggered on my build server or something else I need to do in my automerge config?

Thanks
