### ISSUE TITLE
Cannot use args: "--trace"

### ISSUE THREAD

**Issue by rbubley** [pascalgn/automerge-action#154]
When trying to debug using the approach in the ReadMe:
```
      - name: automerge
        uses: "pascalgn/automerge-action@v0.14.1"
        with:
          args: "--trace"
        env:
          GITHUB_TOKEN: "${{ secrets.GITHUB_TOKEN }}"
          PULL_REQUEST: 266
          MERGE_DELETE_BRANCH: true
```

I get:
```
Warning: Unexpected input(s) 'args', valid inputs are ['']
Run pascalgn/automerge-action@v0.14.1
  with:
    args: --trace
  env:
    pythonLocation: /opt/hostedtoolcache/Python/3.9.5/x64
    LD_LIBRARY_PATH: /opt/hostedtoolcache/Python/3.9.5/x64/lib
    changes: 1
    GITHUB_TOKEN: ***
    PULL_REQUEST: 266
    MERGE_DELETE_BRANCH: true
```
I think this warning is because `args` is not specified as an `input` in `action.yml`?

Although the job goes on to run, there is no debug output.
