### ISSUE TITLE
Q: how to trigger automerge after the checks finish?

### ISSUE THREAD

**Issue by PovilasAtPoq** [pascalgn/automerge-action#170]
I assumed that check_suite type completed would be the check which runs after all checks passes. Howerver, it happened now twice: if PR reviews happens before the build check passes, then it's not being merged.

**My config**
```
name: automerge
on:
  pull_request:
    types:
      - labeled
  pull_request_review:
    types:
      - submitted
  check_suite:
    types:
      - completed
```
**Merge not happening after the checks complete**
![image](https://user-images.githubusercontent.com/44364754/130226904-4e248201-ea48-4247-aa78-d1b399f5320b.png)

**Comment by pascalgn** [comment]
Did you have a look at _all_ the events that triggered automerge-action runs? It might be that the build sends the "status" event and not "check_suite"

**Comment by PovilasAtPoq** [comment]
> Did you have a look at _all_ the events that triggered automerge-action runs? It might be that the build sends the "status" event and not "check_suite"

I did try to look it up, but I couldn't find a reasonable event. I assumed one by default would use such an even so would know how it's called. Hence, posted here.

I will try to add
```
on:
  status
```

Seems that status doesn't have any [types](https://docs.github.com/en/actions/reference/events-that-trigger-workflows#status)

**Comment by pascalgn** [comment]
Yes, it doesn't have any types, see the usage example in the README: https://github.com/pascalgn/automerge-action#usage

**Comment by PovilasAtPoq** [comment]
> Yes, it doesn't have any types, see the usage example in the README: [pascalgn/automerge-action#usage](https://github.com/pascalgn/automerge-action#usage)

thank you 

so i ended up adding

```
	status: {}
```

and just tested, and it merged it! :) Thank you for your help and the auto-merger itself!

**Comment by ddelange** [comment]
For me, `status: {}` does not seem to work, so I went with a manual trigger at the end of the job in question:
```yaml
# CI.yaml
      ...
      # last step of the CI job
      - name: Trigger automerge
        uses: peter-evans/repository-dispatch@v1
        with:
          token: ${{ secrets.TOKEN }}  # generate a personal access token with `public_repo` scope (write access)
          event-type: checks-complete
```
and then explicitly add this event as trigger to the automerge workflow:
```yaml
# automerge.yaml
on:
  # trigger when checks complete (manually triggered as final step of CI workflow)
  repository_dispatch:
    types: [checks-complete]
```
