### ISSUE TITLE
Skipping PR merge, required label missing

### ISSUE THREAD

**Issue by FlamingTuri** [pascalgn/automerge-action#173]
I am encountering the following error when automerge action is triggered by dependabot pull requests:

```
Skipping PR update, required label missing: automerge
```

This is my automerge.yml:

```yaml
name: automerge

on:
  pull_request:
    branches:
      - develop
  workflow_run:
    workflows: ["build"]
    types:
      - completed

jobs:
  log-github-actor:
    runs-on: ubuntu-latest
    steps:
      - run: echo ${{ github.actor }}
  automerge:
    needs: log-github-actor
    if: ${{ github.actor == 'dependabot[bot]' }}
    runs-on: ubuntu-latest
    steps:
      - uses: "pascalgn/automerge-action@v0.14.3"
        env:
          GITHUB_TOKEN: "${{ secrets.GITHUB_TOKEN }}"
          MERGE_LABELS: "dependencies"
          MERGE_COMMIT_MESSAGE: pull-request-title
          MERGE_DELETE_BRANCH: true
          MERGE_METHOD: "rebase"
          MERGE_RETRY_SLEEP: "60000"
```

Dependabot pull requests are created with `dependencies` and `javascript` labels. Am I missing something?
