### ISSUE TITLE
Feature Request: Never automerge if blacklisted folder is changed in PR

### ISSUE THREAD

**Issue by combe15** [pascalgn/automerge-action#175]
I am needing absolute assurance that if any of the commits in a PR touch a specific folder then it won't auto-merge.

Currently, Github's own `paths-ignore:` doesn't work the way I need it to. If any file doesn't fit the `paths-ignore`, then the workflow will run. This is a problem for me because I do not want a PR to edit my `.github` folder. If someone edits a separate file AND the .github folder, then the workflow will run. Another limitation is that if there are 1,000+ commits in a PR or a timeout, then the default is for the workflow to run.

![image](https://user-images.githubusercontent.com/11339091/145172922-a375a4e7-66bb-49ed-a774-fd17990148c3.png)

Here are my current settings:

```YAML
name: automerge
on:
  pull_request_target:
    types: [opened, edited]
    paths-ignore: ['.github/**/*', '.github']

jobs:
  automerge:  # https://github.com/marketplace/actions/merge-pull-requests-automerge-action
    runs-on: ubuntu-latest
    steps:
      - name: automerge
        uses: "pascalgn/automerge-action@v0.14.3"
        env:
          GITHUB_TOKEN: "${{ secrets.GITHUB_TOKEN }}"
          MERGE_LABELS: ""
          MERGE_DELETE_BRANCH: true
```
