### ISSUE TITLE
AutoMerge not working

### ISSUE THREAD

**Issue by sahilreddyifit** [pascalgn/automerge-action#179]
I have a pretty generic setup for automerge as follows:
```
name: automerge
on:
  pull_request:
    types:
      - labeled
      - unlabeled
      - synchronize
      - opened
      - edited
      - ready_for_review
      - reopened
      - unlocked
  pull_request_review:
    types:
      - submitted
  check_suite:
    types:
      - completed
  status: {}
jobs:
  automerge:
    runs-on: ubuntu-latest
    steps:
      - name: automerge
        uses: "pascalgn/automerge-action@v0.14.3"
        env:
          MERGE_LABELS: ""
          MERGE_RETRIES: "32"
          MERGE_RETRY_SLEEP: "60000"
          MERGE_METHOD: "squash"
          GITHUB_TOKEN: "${{ secrets.GITHUB_TOKEN }}"
```

But I'm not able to automerge. I saw this comment (https://github.com/pascalgn/automerge-action/issues/122#issuecomment-948845368) about the merge button needing to be green to stop `mergeable_state` from being blocked. But the action itself produces a status check which doesn't allow the button to be green and `mergeable_state` to be unblocked. Instead of it being green, all of my other status checks pass and the button is grey because the automerge status check is still going. How do I get around this so I can merge when my other status checks have passed?

**Comment by sahilreddyifit** [comment]
This was actually a branch protection issue

**Comment by q-yusufmahtab** [comment]
@sahilreddyifit can you describe the underlying issue please? I'm facing the same thing
![image](https://github.com/user-attachments/assets/6eddc0e9-21d5-4004-bf5b-2bdfc5d7faaa)

**Comment by q-yusufmahtab** [comment]
I just noticed the logs say

```log
2024-07-26T15:55:19.324Z INFO  Skipping PR update, required label missing: automerge
```

but here's my configuration:

```yaml
      - name: Automerge PR
        uses: pascalgn/automerge-action@v0.16.3
        env:
          GITHUB_TOKEN: "${{ secrets.GITHUB_TOKEN }}"
          MERGE_LABELS: ready-to-merge
          MERGE_METHOD: squash
          MERGE_DELETE_BRANCH: true
```

Very strange...
