### ISSUE TITLE
ΒUG: Unable to bypass branch protection rules

### ISSUE THREAD

**Issue by pantelis-karamolegkos** [pascalgn/automerge-action#200]
I use the action as follows

```
      - name: merge the PR
        uses: pascalgn/automerge-action@v0.15.5
        env:
          MERGE_ERROR_FAIL: true
          MERGE_LABELS: "${{ env.AUTOMERGE_LABEL }}"
          MERGE_COMMIT_MESSAGE: ${{ env.MERGE_COMMIT_MESSAGE }}
          MERGE_METHOD: ${{ env.MERGE_METHOD }}
          GITHUB_TOKEN: "${{ secrets.GH_TOKEN }}"
```

My repo settings:
![Screenshot 2022-10-30 at 9 18 15 PM](https://user-images.githubusercontent.com/50835081/198897377-b96f6fed-b122-4bf4-a535-6c77e3cba624.png)

the `${{ secrets.GH_TOKEN }` is my PAT and I am a member of a team that can 

> dismiss pull request reviews

AND

> Allow specified actors to bypass required pull requests

However merge fails:

```
...
2022-10-30T19:15:05.307Z INFO  Current PR status: mergeable_state: blocked
2022-10-30T19:15:05.307Z ERROR PR not ready to be merged after 6 tries
```

isn't that a bug?
