### ISSUE TITLE
Old configuration option present: LABELS

### ISSUE THREAD

**Issue by SteveBox0** [pascalgn/automerge-action#202]
I am getting "`ERROR Old configuration option present: LABELS`" but the action workflow does not have any labels present. Any suggestions to fix this?

```
      - name: Merge pull requests (automerge-action)
        uses: pascalgn/automerge-action@v0.15.5
        env:
          GITHUB_TOKEN: "${{ secrets.GITHUB_TOKEN }}"
          MERGE_METHOD: squash
          MERGE_DELETE_BRANCH: true
```
