### ISSUE TITLE
UPDATE_RETRY_SLEEP and UPDATE_RETRIES does not respect label

### ISSUE THREAD

**Issue by gfrid** [pascalgn/automerge-action#209]
scenario:
to auto merge label is required
a comment in pr is required "/approved"

code owner can comment /approve before the checks and labels are passed, the automerge ignores label checking
i think there is should be a functionality to retry if label does not exist since label can appear after check
and comment can appear before check

         
 UPDATE_RETRIES: "15"  
 UPDATE_RETRY_SLEEP: "60000" 
 MERGE_RETRIES: "15"
 MERGE_RETRY_SLEEP: "60000"

**Comment by pascalgn** [comment]
I'm not 100% sure I understand the question correctly, but in the README, the recommended configuration is
```yaml
name: automerge
on:
  pull_request:
    types:
      - labeled     # <-- !!!
      - unlabeled
      - synchronize
      - opened
      - edited
      - ready_for_review
      - reopened
      - unlocked
[...]
```
so when a label is added to the PR, the action should be triggered again. When the action is triggered again, the e.g. UPDATE_RETRY_SLEEP from the _previous_ action run doesn't matter (it only matters during 1 action run)

Does that help in any way?
