### ISSUE TITLE
Missing commit if merge happens right after it

### ISSUE THREAD

**Issue by Willy-JL** [pascalgn/automerge-action#217]
I set up a workflow that runs when the repo owner approves a PR to:
- do some last checks
- update a config version number and commit it
- merge the PR with this action
- make a release from the base branch after the merge

It all goes perfectly, except that the merge happens right after the commit to the PR so this commit is not included when merging...

Commit was added fine in the PR:
![image](https://user-images.githubusercontent.com/49810075/224150023-390024d6-3acf-4533-8309-484223c0c256.png)

But not included in merge:
![image](https://user-images.githubusercontent.com/49810075/224150356-8c369a85-3e36-44f4-aa1c-25a0fee1bba9.png)

This is a stripped version of my workflow:
```yaml
on:
  pull_request_review:
    types: [submitted]

jobs:
  release:
    if: ... (check its the repo owner approving changes)
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: "Update version number"
        run: ...

      - name: "Commit new version number"
        uses: EndBug/add-and-commit@v9
        with:
          default_author: github_actions
          message: Update version number
          add: '...'

      - name: "Merge pull request"
        uses: "pascalgn/automerge-action@v0.15.6"
        env:
          MERGE_LABELS: ""
          GITHUB_TOKEN: "${{ secrets.GITHUB_TOKEN }}"

      - name: "Make release"
        uses: softprops/action-gh-release@v1
        with:
          body_path: "..."
          draft: false
          prerelease: false
          files: ...
          name: "${{ env.RELEASE_TAG }}"
          tag_name: "${{ env.RELEASE_TAG }}"
          target_commitish: main
```

How could i fix this? Is there an option i can pass to the action to make sure the PR is updated? Or should i just add some hard-coded delay?
