### ISSUE TITLE
Failed to merge PR: Changes must be made through the merge queue

### ISSUE THREAD

**Issue by larabear** [pascalgn/automerge-action#235]
The branch has "Require merge queue" setting on, and I'm getting the error "Failed to merge PR: Changes must be made through the merge queue". How can I configure the workflow in order to merge the PR with merge queue?

Here's my step:

```
...
      - name: Merge
        uses: pascalgn/automerge-action@v0.14.3
        if: steps.waitforstatuschecks.outputs.status == 'success'
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          MERGE_LABELS: ""
          MERGE_METHOD: squash
```
