### ISSUE TITLE
bug: Invalid workflow file

### ISSUE THREAD

**Issue by pythoninthegrass** [pascalgn/automerge-action#239]
In the [outputs example usage](https://github.com/pascalgn/automerge-action/blob/main/README.md?plain=1#L276), this is the most likely deprecated GitHub Actions syntax:
```yaml
- name: feedback
        if: steps.automerge.outputs.mergeResult == "merged"
        run: |
          echo "Pull request ${{ steps.automerge.outputs.pullRequestNumber }} merged!"
```
Whereas working conditional code uses yaml curly brackets:
```yaml
- name: feedback
        if: ${{ steps.automerge.outputs.mergeResult == 'merged' }}
        run: |
          echo "Pull request ${{ steps.automerge.outputs.pullRequestNumber }} merged!"
```

**Full error**
>  Invalid workflow file: .github/workflows/automerge.yml#L48
> The workflow is not valid. .github/workflows/automerge.yml (Line: 48, Col: 13): Unexpected symbol: '"merged"'. Located at position 40 within expression: steps.automerge.outputs.mergeResult == "merged"
