### ISSUE TITLE
Publish to github registry

### ISSUE THREAD

**Issue by chenrui333** [pascalgn/automerge-action#24]
Right now, you have to build the container every time, it would be nice to publish this into github registry or some other docker registry.

https://help.github.com/en/github/automating-your-workflow-with-github-actions/workflow-syntax-for-github-actions#example-using-a-docker-public-registry-action

**Comment by lawliet89** [comment]
Github Actions have become GA and the minutes for private repositories have become chargeable. This will help save some minutes.

**Comment by pascalgn** [comment]
I understand the need for this, but unfortunately this feature does not seem to be ready yet, see this forum thread: https://github.community/t5/GitHub-Actions/docker-pull-from-public-GitHub-Package-Registry-fail-with-quot/td-p/32782

However, I have pushed [v0.6.0 to docker.pkg.github.com](https://github.com/pascalgn/automerge-action/packages/57371) now, so when GH enables the feature, you should be able to switch to using the pre-built Docker image immediately.

For security reasons, I recommend to use the full SHA, when referencing the Docker image (as I also recommend when referencing the action from GH directly). So the workflow file should look like this:

```yaml
# [...]
jobs:
  automerge:
    runs-on: ubuntu-latest
    steps:
      - name: automerge
        uses: "docker://docker.pkg.github.com/pascalgn/automerge-action/automerge-action:c7859ab63774304798c4dd36ed106b59bbf728974117a9f350cac756d80d9e37"
        # [...]
```

(the usual Docker syntax would be `docker.pkg.github.com/pascalgn/automerge-action/automerge-action@sha256:c7859ab63774304798c4dd36ed106b59bbf728974117a9f350cac756d80d9e37`, but for some reason GH chose to use a slightly different syntax here)

Also, I pushed that image manually, but when someone finds a good example where the action is automatically built and pushed to docker.pkg.github.com, feel free to link it here!

I will leave this issue open until GH fully supports pulling from docker.pkg.github.com in actions.
