### ISSUE TITLE
ERROR  fetch is not set. Please pass a fetch implementation as new Octokit({ request: { fetch }}). Learn more at https://github.com/octokit/octokit.js/#fetch-missing

### ISSUE THREAD

**Issue by TheSuperiorStanislav** [pascalgn/automerge-action#243]
New version(0.16.0) now throws this error 
```
fetch is not set. Please pass a fetch implementation as new Octokit({ request: { fetch }}). Learn more at https://github.com/octokit/octokit.js/#fetch-missing
```
Usage
```
- name: Merge pull request
  id: automerge
  uses: pascalgn/automerge-action@v0.16.0
  env:
    MERGE_LABELS: automated-pr  # Defines which PR labels should be automatically merged
    MERGE_REQUIRED_APPROVALS: 2
    GITHUB_TOKEN:  ${{ steps.generate-token.outputs.token }}
```
