### ISSUE TITLE
Merge on specific label?

### ISSUE THREAD

**Issue by Fristi** [pascalgn/automerge-action#25]
Hi!

Thanks for this Github action, I think it can very valueable :)

I would like to merge PR's with the label `update` and which have been successfully built. However I see this message on github actions:

```
INFO  Event name: pull_request
INFO  Updating PR #566 Update apm-opentracing to 1.10.1
INFO  No matching labels found on PR, skipping

```

With this configuration:

```
name: automerge
on:
  pull_request:
    types:
      - labeled
      - unlabeled
      - synchronize
      - opened
      - edited
      - ready_for_review
      - reopened
      - unlocked
  pull_request_review:
    types:
      - submitted
  status: {}
jobs:
  automerge:
    runs-on: ubuntu-latest
    steps:
      - name: automerge
        uses: "pascalgn/automerge-action@f84dd310ea4a19890c70a4ff11ab282a872fb94b"
        env:
          GITHUB_TOKEN: "${{ secrets.GITHUB_TOKEN }}"
          LABELS: "update"
          MERGE_METHOD: "squash"
          COMMIT_MESSAGE_TEMPLATE: "pull-request-title" 
```
