### ISSUE TITLE
Override `MERGE_METHOD` with labels?

### ISSUE THREAD

**Issue by chancancode** [pascalgn/automerge-action#26]
Hello! First of all, this is great! Thank you for sharing your code!

Would it be possible to allow labels to override the `MERGE_METHOD`? I ask because we usually prefer the `merge` method, but occasionally, a contributor will open a PR with many commits, in which case it would be better to use the `squash` method.

Since this action uses environment variables, I think I can do that myself by running a step to set the variable before running this action, but it would be great if that feature is built-in!

**Comment by pascalgn** [comment]
I think the easiest solution would be to create 2 action workflows, maybe one named `automerge.yml` (following the documentation in the [README](https://github.com/pascalgn/automerge-action)), and one named `autosquash.yml` which is a copy, with the following configuration:

```yaml
        env:
          GITHUB_TOKEN: "${{ secrets.GITHUB_TOKEN }}"
          MERGE_LABELS: "autosquash"
          MERGE_METHOD: "squash"
```
