### ISSUE TITLE
PAT not used when merging PRs

### ISSUE THREAD

**Issue by migheorghe** [pascalgn/automerge-action#269]
I have a weird behavior when using this action to automerge PRs. The action is configured to use a PAT instead of the default GITHUB_TOKEN and most of the times it merges the PRs using my account. However every once in a while it merges the PRs with gihub-actions user and I can't explain this behavior.  Does ayone has any idee of what it might happen and how can I fix this?

```
    steps:
      - id: automerge-pat
        name: automerge-pat
        uses: "pascalgn/automerge-action@v0.16.3"
        env:
          GITHUB_TOKEN: "${{ secrets.FF_AUTO_PAT }}"
          MERGE_LABELS: "automerge,!WIP,!WORK IN PROGRESS,!wip,!work in progress"
          MERGE_DELETE_BRANCH: true
          MERGE_METHOD: rebase
          LOG: "TRACE"
          MERGE_RETRIES: "10"
          MERGE_RETRY_SLEEP: "5000"
          MERGE_REQUIRED_APPROVALS: "0"
```
