### ISSUE TITLE
ERROR Not Found when running automerge action

### ISSUE THREAD

**Issue by Alexander-Scott** [pascalgn/automerge-action#29]
Hi, this is my workflow file:

```
name: CI

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - build
    - test
    - etc...
  automerge:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: automerge
        uses: "pascalgn/automerge-action@733fcc62d711705eae9cd66fcf49c93c1d1a98c6"
        env:
          GITHUB_TOKEN: "${{ secrets.MergeBot }}"  
```

When the automerge job runs it fails with:

```
Run pascalgn/automerge-action@733fcc62d711705eae9cd66fcf49c93c1d1a98c6
INFO  Event name: push
ERROR Not Found
##[error]Docker run failed with exit code 1
```

Any ideas what this error is and what it cannot find? The preceeding build job runs successfully and is a required check. The branch is a protected branch in a private repository. The Github token is correct. The 'automerge' label is set on the PR.
