### ISSUE TITLE
Is there a way to bypass "Waiting on code owner review"?

### ISSUE THREAD

**Issue by ThomasVerhoeven1998** [pascalgn/automerge-action#290]
Currently, I want to automatically merge PRs with a label "automerge". Whenever the status checks like build and sonar are passed it should be able to automatically merge? 

But the automerge action is blocking on the fact that it's waiting on code owner reviews from specifiek groups

Current setup is like this: 

```
name: automerge
on:
    pull_request:
        types:
            - labeled
            - unlabeled
            - synchronize
            - opened
            - edited
            - ready_for_review
            - reopened
    check_suite:
        types:
            - completed
    status: {}
jobs:
    automerge:
        runs-on: ubuntu-latest
        steps:
            - name: automerge
              uses: "pascalgn/automerge-action@v0.16.4"
              env:
                  GITHUB_TOKEN: "${{ secrets.GITHUB_TOKEN }}"
                  MERGE_LABELS: "automerge"
                  #MERGE_FILTER_AUTHOR: "jenkins"
                  MERGE_DELETE_BRANCH: "true"
                  UPDATE_RETRIES: "10"
                  UPDATE_RETRY_SLEEP: "10000"
                  MERGE_RETRIES: "10"
                  MERGE_RETRY_SLEEP: "300000"
                  MERGE_REQUIRED_APPROVALS: "0"
```

Not sure whats wrong?
