### ISSUE TITLE
Github push action not triggered after the github bot automerge.

### ISSUE THREAD

**Issue by Mariappan** [pascalgn/automerge-action#34]
**Issue:**
I have a repo with two github actions

_Test repo:_ https://github.com/Mariappan/gh-actions

```
name: Tag repository with version on version change

on:
  push:
    branches:
      - master
    paths:
      - config/VERSION

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Push tag
      run: |
        if git diff --exit-code HEAD^ -- config/VERSION; then
          echo "No change in VERSION:`cat config/VERSION`."
        else
          tag="v$(cat config/VERSION)"
          git tag "${tag}"
          git push "https://${GITHUB_ACTOR}:${{ secrets.GITHUB_TOKEN }}@github.com/${GITHUB_REPOSITORY}.git" refs/tags/"${tag}"
        fi
```

```
name: Automatically merge pull requests on certain labels
on:
  pull_request:
    types:
      - labeled
      - synchronize
      - opened
      - edited
      - ready_for_review
      - reopened
      - unlocked
  pull_request_review:
    types:
      - submitted
  check_run:
    types:
      - completed
jobs:
  automerge:
    runs-on: ubuntu-latest
    steps:
      - uses: "pascalgn/automerge-action@v0.4.2"
        env:
          GITHUB_TOKEN: "${{ secrets.GITHUB_TOKEN }}"
          MERGE_LABELS: "mergeready,!donotmerge,!after next release"
          MERGE_METHOD: "squash"
          UPDATE_LABELS: "mergeready"
          UPDATE_METHOD: "merge"
```

When i merge the PR manually, the tag action gets triggered .
But when the same PR is merged by automerge-action, the tag action is not getting triggered.

Is this the known issue ?? Any thoughts ?
