### ISSUE TITLE
Enhancement: Support issue_comment github.event_name/type

### ISSUE THREAD

**Issue by trilom** [pascalgn/automerge-action#55]
It would be nice to support this.  I don't know what the limitations are but here is a potential implementation.

In this potential implementation I have added 2 options either a PR event payload or a PR number, your container can take either input and use this instead of requiring the source to be a pull_request event_name, does this make sense?

Thanks

```yaml
name: automerge
env:
  pr_number: ${{ format('{0}{1}', github.event.pull_request.number, github.event.issue.number) }}
on:
 issue_comment automerge does not work for now
   issue_comment:
     types: 
       - created
  pull_request:
    types:
      - labeled
      - closed
jobs:
  automerge:
    name: automerge pr
    runs-on: ubuntu-latest
# if event type is PR or comment on PR from trilom with '/release'
    if: >-
      github.event_name == 'pull_request' 
      || (
        github.event_name == 'issue_comment' 
        && github.event.issue.pull_request != '' 
        && contains(github.event.comment.body, '/release') 
        && github.actor == 'trilom')
    steps:
# if failure, get payload of PR and notify
      - name: get pr payload
        uses: actions/github-script@0.8.0
        id: pr_json
        with:
          github-token: ${{env.GITHUB_TOKEN}}
          result-encoding: string
          script: |
            const result = await github.pulls.get({
              owner: context.payload.repository.owner.name,
              repo: context.payload.repository.name,
              pull_number: ${{ env.pr_number }}
            })
            return result.data;
      - name: automerge pr
        uses: pascalgn/automerge-action@v0.7.5
        env:
          PR_NUMBER: ${{ env.pr_number }}
          PR_PAYLOAD: ${{ steps.pr_json.outputs.result }}
          GITHUB_TOKEN: ${{ env.GITHUB_TOKEN }}
          MERGE_METHOD: merge
          MERGE_COMMIT_MESSAGE: 'Auto merge PR#{pullRequest.number}: {pullRequest.title}'
          UPDATE_METHOD: merge
          MERGE_LABELS: 'tested'
          UPDATE_LABELS: ''
      - name: if failure, set pr payload outputs
        id: pr
        run: |
          echo '${{ steps.pr_json.outputs.result }}' > pr.json
          echo "::set-output name=user::$( jq -r '.user.login' pr.json )"
          echo "::set-output name=head::$( jq -r '.head.repo.full_name' pr.json )"
          echo "::set-output name=head_url::$( jq -r '.head.repo.html_url' pr.json )"
          echo "::set-output name=base::$( jq -r '.base.repo.full_name' pr.json )"
          echo "::set-output name=base_url::$( jq -r '.base.repo.html_url' pr.json )"
      - name: if failure, notify
        uses: peter-evans/create-or-update-comment@v1
        # if: failure()
        with:
          token: ${{ env.GITHUB_TOKEN }}
          issue-number: ${{ env.pr_number }}
          body: |
            @${{ steps.pr.outputs.user }}, @trilom - it appears that there was an issue with the merge.

            Head Repo/Branch: **[${{ steps.pr.outputs.head }}]**(${{ steps.pr.outputs.head_url }}) merge into **[${{ steps.pr.outputs.base }}]**(${{ steps.pr.outputs.base_url }})
            
            ## Event JSON
            ```json
              ${{ toJSON(steps.pr_json.outputs.result)}}
            
            ## Event JSON
            ```json
              ${{ toJSON(steps.pr.outputs.result)}}
            ```

```
