### ISSUE TITLE
MERGE_REMOVE_LABELS will remove repository label

### ISSUE THREAD

**Issue by echoulen** [pascalgn/automerge-action#56]
as title

my setting

```yml
name: automerge
on:
  pull_request:
    types:
      - labeled
      - unlabeled
      - synchronize
      - opened
      - edited
      - ready_for_review
      - reopened
      - unlocked
  pull_request_review:
    types:
      - submitted
  status: {}
jobs:
  automerge:
    runs-on: ubuntu-latest
    steps:
      - name: automerge
        uses: "pascalgn/automerge-action@ccae530ae13b6af67a7a2009c266fe925844e658"
        env:
          GITHUB_TOKEN: "${{ secrets.GITHUB_TOKEN }}"
          MERGE_LABELS: ready
          MERGE_REMOVE_LABELS: ready
          MERGE_METHOD: squash
          MERGE_RETRY_SLEEP: 90000
          MERGE_RETRIES: 20
          UPDATE_LABELS: ""
```
