### ISSUE TITLE
Question: PR merged not trigger pull_request.closed

### ISSUE THREAD

**Issue by echoulen** [pascalgn/automerge-action#57]
In my case
> .github/workflows/notify.yml
```
name: notify
on:
  pull_request:
    types:
      - opened
      - reopened
      - closed
jobs:
  notify:
    runs-on: ubuntu-latest
    steps:
    - name: Google Chat Notification
      uses: CommonMarvel/google-chat-notification@master
      with:
        url: ${{ secrets.GOOGLE_CHAT_WEBHOOK }}
```

The workflow will not trigger if the PR merged by `automerge-action`,
but working fine if I merge PR manually.
