### ISSUE TITLE
Merge title repeated in commit messages

### ISSUE THREAD

**Issue by silviogutierrez** [pascalgn/automerge-action#72]
First off: incredible library. Took me seconds to setup. My work flow prior to this action:

1. Squash merges
2. Fill out the commit title, but not the commit body, in the image below:

<img width="681" alt="image" src="https://user-images.githubusercontent.com/92824/79676763-59929b80-81b7-11ea-8300-14d2615ae215.png">

This makes my commit history concise. Occasionally, if I have a large PR, I'll add something in the second box.

However, if I create a PR and automerge it, the library currently sets the commit title *and* the description to the PR title. Title was "Another really nice one" and the description was purposely empty. Image below:

<img width="455" alt="image" src="https://user-images.githubusercontent.com/92824/79676798-a70f0880-81b7-11ea-9ea2-88cf1bb0af0c.png">

This is because the notion of separate title and message is a *github* concept. It does not exist in Git, where it is a single field separated by newlines.

The fix was easy, but there are other cases to consider (like when you *do* want a body).

See here:

https://github.com/pascalgn/automerge-action/compare/master...silviogutierrez:debug-commit?expand=1

The above is just hack-ey to try it out.

Properly, commit message needs to be renamed to commit title, and sourced from PR title. Then a *new* variable introduced to hold commit message, which should be one of: "PR description", "log of commits", etc.

Happy to contribute if you're open to this idea. Thanks again for your work.

PS. If it's useful, here is my current `automerge-action` below (using my fork to test)

```
name: automerge
on:
    pull_request:
        types:
            - labeled
            - unlabeled
            - synchronize
            - opened
            - edited
            - ready_for_review
            - reopened
            - unlocked
    # pull_request_review:
    #   types:
    #     - submitted
    check_suite:
        types:
            - completed
    status: {}
jobs:
    automerge:
        runs-on: ubuntu-latest
        steps:
            - name: automerge
              uses: "silviogutierrez/automerge-action@0398825ebbf817dfa8a537e779af4da7ac11d364"
              env:
                  GITHUB_TOKEN: "${{ secrets.GITHUB_TOKEN }}"
                  MERGE_METHOD: squash
                  MERGE_COMMIT_MESSAGE: pull-request-title
                  MERGE_DELETE_BRANCH: true
```
