### ISSUE TITLE
Bug: Instead of removing the label from the PR, it deletes the label from the repo entirely

### ISSUE THREAD

**Issue by iansan5653** [pascalgn/automerge-action#80]
I have `MERGE_REMOVE_LABELS` set to configure the bot to remove the `automerge` label from the PR after merging it. This it does successfully, but not by removing the label from the PR. Instead, it deletes the label from the workspace entirely, so I have to create a new label every single time I want to auto merge a PR. Also, I can't have two automerged queued because the label will get deleted when the first is merged.

Here's my entire config:
```yml
name: automerge
on:
  pull_request:
    types:
      - labeled
      - unlabeled
      - synchronize
      - opened
      - edited
      - ready_for_review
      - reopened
      - unlocked
  pull_request_review:
    types:
      - submitted
  check_suite:
    types:
      - completed
  status: {}
jobs:
  automerge:
    runs-on: ubuntu-latest
    steps:
      - name: automerge
        uses: "pascalgn/automerge-action@80acb0f883348dcfd0e526288f7d27a12b9333be"
        env:
          GITHUB_TOKEN: "${{secrets.BOT_TOKEN}}"
          MERGE_REMOVE_LABELS: automerge
          MERGE_METHOD: squash
          MERGE_DELETE_BRANCH: true
```
