### ISSUE TITLE
Add example for new .yml files

### ISSUE THREAD

**Issue by DanielHabenicht** [pascalgn/automerge-action#9]
Hi, thanks for this action.

There is no example for .yml file configuration and I find it hard to add this action without an example. 

Maybe I will provide a PR if I find out how it is used.

**Comment by pascalgn** [comment]
Thanks for the feedback! The new actions API has not been a priority for me so far, but I will try to update the documentation in the next days.

The feature is still in beta and I think GH is still actively developing it, at least the documentation does not look 100 % finished yet. What I found is:

- https://help.github.com/en/categories/automating-your-workflow-with-github-actions
- https://help.github.com/en/articles/about-actions#types-of-github-actions
- https://help.github.com/en/articles/configuring-a-workflow

If you save this file in your repository as `.github/workflows/automerge.yml`, I think it should work, at least it's triggering something in my case.

```yaml
name: automerge
on: [pull_request, pull_request_review, status]
jobs:
  automerge:
    runs-on: ubuntu-latest
    steps:
      - name: automerge
        uses: "pascalgn/automerge-action@ef030fabb510b9a5a3bc2e3a0123638e11e72541"
        env:
          GITHUB_TOKEN: "${{ secrets.GITHUB_TOKEN }}"
```

It could be that the action also needs to be adapted, as previously exit code 78 meant "neutral exit", useful to indicate that nothing was done, but with the new workflow model, GH seems to report this as error.

**Important:** You also need to upgrade the repository to use the new actions model, otherwise GH will still use the old workflow file.

**Comment by DanielHabenicht** [comment]
Thanks for the Example!

I can confirm that it is returning with an error, hopefully it will get fixed. Till then I added `continue-on-error` option:
```yml
 - name: Merge pull requests
      uses: pascalgn/automerge-action@v0.2.4
      continue-on-error: true
      env: 
```

**Comment by roni-frantchi** [comment]
I'm also getting an error:
```
- There was an unexpected error when executing this Action. For help debugging what went wrong, please contact support@github.com. The unique ID for this error is 947C:6EFE:D292:2F2EF:5D626E56
```

**Comment by pascalgn** [comment]
@roni-frantchi This is a problem unrelated to this issue. From the message I'm guessing it's when using the old GH actions (main.workflow). I've seen this message sometimes already and contacted GH support about it, but they don't know what's causing it; it should help to just rerun the action for now

**Comment by DanielHabenicht** [comment]
I've contacted GitHub Support aswell - same answer. 
![image](https://user-images.githubusercontent.com/13590797/63670745-ec706700-c7dd-11e9-954f-b31c382f1b1a.png)

**Comment by roni-frantchi** [comment]
Thanks @pascalgn @DanielHabenicht !

> From the message I'm guessing it's when using the old GH actions (main.workflow)
```yml
# .github/workflows/automerge.yml 

name: automerge
on: [pull_request, pull_request_review, status]
jobs:
  automerge:
    runs-on: ubuntu-latest
    steps:
      - name: automerge
        uses: "pascalgn/automerge-action@ef030fabb510b9a5a3bc2e3a0123638e11e72541"
        continue-on-error: true
        env:
          GITHUB_TOKEN: "${{ secrets.GITHUB_TOKEN }}"
```
Here's how I've used it:

>it should help to just rerun the action for now

Rerunning fails with the same error

**Comment by roni-frantchi** [comment]
By the way, the failure seems to always be related to status changes:
`automerge / .github/workflows/automerge.yml (status) `
Perhaps it is so when there are other workflows that update the status while it's running?..

**Comment by DanielHabenicht** [comment]
Well for me it is only failing with the GitHub error on the master branch.

**Comment by pascalgn** [comment]
For me I'm also getting the message `INFO  No update done due to PR state unknown` when running with the new GH actions workflow.

I think this could be because the action is running and therefore GH is reporting the PR state as "unknown" while the action is running... I'm having a look into it

**Comment by pascalgn** [comment]
There also seem to be other issues with the new GH actions. For example, the action will not be invoked anymore when a label has been added to the PR. This is unfortunate, as we sometimes wait until a PR looks ready and then add the "automerge" label and let the action do the rest.

This is already a known issue: https://github.community/t5/GitHub-API-Development-and/pull-request-action-does-not-run-on-merge/m-p/29847#M2738

So far it looks like the new GH actions model is not 100 % usable yet. Unfortunately, there is not much I can do at this moment other than waiting for GH to fix these issues.

**Comment by bjchambers** [comment]
It sounds like you can request it to run on label changes by overriding the `types` it runs on:

```
on:
  pull_request:
    types: [labeled, unlabeled, opened, edited, ready_for_review, reopened]
```

**Comment by pascalgn** [comment]
The new action model seems to be usable now, so I've updated the documentation!

If you run into any problems, please create an issue, of course! 👍

**Comment by roni-frantchi** [comment]
Hi @pascalgn I'm still getting:
```
- There was an unexpected error when executing this Action. For help debugging what went wrong, please contact support@github.com. The unique ID for this error is 44AF:0E54:2695E:78D08:5D875ADA
```

I get that failure only on the "on: status" trigger.  

Using the following `.github/workflows/automerge.yml`:
```yml
name: automerge
on:
  pull_request:
    types:
      - labeled
      - unlabeled
      - synchronize
      - opened
      - edited
      - ready_for_review
      - reopened
      - unlocked
  pull_request_review:
    types:
      - submitted
  status: {}        # removing this seems to resolve the issue, but then I don't get automerge triggers after status updates (ci etc.)
  
jobs:
  automerge:
    runs-on: ubuntu-latest
    steps:
      - name: automerge
        uses: "pascalgn/automerge-action@master"
        env:
          GITHUB_TOKEN: "${{ secrets.GITHUB_TOKEN }}"
          LABELS: "!wip,!work in progress"
          AUTOMERGE: "ready to merge"
          AUTOREBASE: "autorebase"
          MERGE_METHOD: "squash"

```

**Comment by pascalgn** [comment]
I think this is unrelated to the automerge-action, see https://github.com/pascalgn/test-status/pull/5

The action there still fails, even though the config is just

```yaml
name: automerge
on: status
jobs:
  automerge:
    runs-on: ubuntu-latest
    steps:
      - run: env
```

As I said above: "So far it looks like the new GH actions model is not 100 % usable yet"

I will write an email to GH support again, but don't hold your breath... (judging from their response time so far)
