### ISSUE TITLE
Merge check runs before checks are finished

### ISSUE THREAD

**Issue by verschoof** [pascalgn/automerge-action#91]
<img width="937" alt="image" src="https://user-images.githubusercontent.com/1527863/86899448-4c2be400-c10a-11ea-939e-d38569f12505.png">

automerge.yml:
```
name: automerge
on:
  pull_request:
    types:
      - labeled
      - unlabeled
      - synchronize
      - opened
      - edited
      - ready_for_review
      - reopened
      - unlocked
  pull_request_review:
    types:
      - submitted
  check_suite:
    types:
      - completed
  status: {}
jobs:
  automerge:
    runs-on: ubuntu-latest
    steps:
      - name: automerge
        uses: "pascalgn/automerge-action@4536e8847eb62fe2f0ee52c8fa92d17aa97f932f"
        env:
          GITHUB_TOKEN: "${{ secrets.GITHUB_TOKEN }}"
```

I copied the example in the docs, but it seems not to work, do I miss something here?
